repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: detect-private-key
        description: Checks for presence of private keys
    -   id: detect-aws-credentials
        description: Checks for AWS credentials