version = 0.1
[default.deploy.parameters]
stack_name = "mortgage-simulator"
resolve_s3 = true
s3_prefix = "mortgage-simulator"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []
